### ISSUE TITLE
Right job name ?  in prometheus.yml config

### ISSUE THREAD

**Issue by stratanic** [DoTheEvo/veeam-prometheus-grafana#1]
Hi, 

question : this job name in pushgateway  has to be...

![image](https://user-images.githubusercontent.com/128167842/227371151-5d7f9a66-105b-4422-b068-4811194146fd.png)

 the same name of :  job in prometheus.yml (config file prometheus) ?

- job_name: "**veeam_report**"  --> ??
    scrape_interval: '120s'
    static_configs:
      - targets: ['localhost:9091']
        labels:
            honor_labels:  true 

my job have the name of "- job_name: value"pushgateway-scrape" not veeam_report.... why?
my data is exactly the same of your picture at pushgateway  Web page.

Thanks.

**Comment by stratanic** [comment]
Sorry, now i know what is honor labels....

My honor label is placed at wrong place.

**Comment by DoTheEvo** [comment]
Added a note on that, cuz I too had to google as I forgot reading about it and just used it.
