### ISSUE TITLE
had picture how change query name

### ISSUE THREAD

**Issue by stratanic** [DoTheEvo/veeam-prometheus-grafana#2]
can you add picture when you say change query name , its not really easy to find first time.

![image](https://user-images.githubusercontent.com/128167842/227657060-ea465fe3-f920-4e39-a781-4ff5c8de2a2e.png)

**Comment by stratanic** [comment]
can someone help me : for legend part.
Why I can't rename legend with mapping.

![image](https://user-images.githubusercontent.com/128167842/228227370-f19e3218-f386-453c-ad66-eba502df3895.png)

**Comment by DoTheEvo** [comment]
big update and rewrite of everything, put there gif for renaming
